export type PosBackorderForFulfillLine = {
  id: string;
  lineNumber: number;
  productId: string | null;
  productVariantId: string | null;
  productName: string;
  productSku: string | null;
  variantName: string | null;
  quantity: number;
  unitPrice: number;
  discountAmount: number;
  taxRate: number;
  taxAmount: number;
  subtotal: number;
  total: number;
  unitOfMeasure: string | null;
  saleUnitSymbol: string | null;
  stockBaseUnitSymbol: string | null;
  stockBaseQtyPerCountSaleUnit: number | null;
  unitAllowDecimals: boolean;
  availableStock: number | null;
  availableStockBase: number | null;
};

export type PosBackorderForFulfill = {
  id: string;
  documentNumber: string;
  transactionType: string;
  status: string;
  createdAt: string;
  subtotal: number;
  taxAmount: number;
  discountAmount: number;
  total: number;
  customerId: string | null;
  customerName: string | null;
  customerDocument: string | null;
  branchName: string | null;
  pointOfSaleName: string | null;
  reservationStatus: string;
  depositAmount: number;
  depositConsumedAmount: number;
  depositAvailable: number;
  lines: PosBackorderForFulfillLine[];
};
