import { TransactionType } from '@modules/transactions/domain/transaction.entity';

/**
 * Siglas cortas para folios correlativos `{CODE}{YY}{NNNNN…}` por sucursal + tipo + año.
 * Mínimo 5 dígitos en el correlativo; sin guiones. Conviven con `DOCUMENT_PREFIXES` (legacy).
 */
export const DOCUMENT_TYPE_CODES: Record<TransactionType, string> = {
  [TransactionType.SALE]: 'VTA',
  [TransactionType.SALE_RETURN]: 'DEV',
  [TransactionType.CUSTOMER_CREDIT_NOTE]: 'NCC',
  [TransactionType.CUSTOMER_CREDIT_NOTE_PAYOUT]: 'NCL',
  [TransactionType.PURCHASE]: 'CMP',
  [TransactionType.PURCHASE_ORDER]: 'OC',
  [TransactionType.PURCHASE_RETURN]: 'DPC',
  [TransactionType.SUPPLIER_INVOICE]: 'FPR',
  [TransactionType.SUPPLIER_RECEIPT]: 'BPR',
  [TransactionType.SUPPLIER_HONORARIUM_RECEIPT]: 'BHP',
  [TransactionType.SUPPLIER_GUIDE]: 'GDP',
  [TransactionType.SUPPLIER_CREDIT_NOTE]: 'NCP',
  [TransactionType.CUSTOMER_ORDER]: 'PCL',
  [TransactionType.QUOTATION]: 'COT',
  [TransactionType.BACKORDER]: 'ECG',
  [TransactionType.SERVICE_ORDER]: 'OTS',
  [TransactionType.PRODUCTION_BATCH]: 'LPR',
  [TransactionType.TRANSFER_OUT]: 'TSO',
  [TransactionType.TRANSFER_IN]: 'TSI',
  [TransactionType.ADJUSTMENT_IN]: 'AJP',
  [TransactionType.ADJUSTMENT_OUT]: 'AJN',
  [TransactionType.INVENTORY_COUNT]: 'INV',
  [TransactionType.INVENTORY_RESERVATION]: 'RES',
  [TransactionType.INVENTORY_BLOCK]: 'BLQ',
  [TransactionType.INVENTORY_UNBLOCK]: 'DBL',
  [TransactionType.PAYMENT_IN]: 'REC',
  [TransactionType.SUPPLIER_PAYMENT]: 'PAG',
  [TransactionType.PAYROLL_PAYMENT]: 'PRM',
  [TransactionType.EXPENSE_PAYMENT]: 'PGO',
  [TransactionType.BANK_TO_CASH_TRANSFER]: 'BCT',
  [TransactionType.PAYROLL]: 'NOM',
  [TransactionType.TIP_PAYOUT]: 'TPP',
  [TransactionType.TIP_PAYOUT_LINE]: 'TPL',
  [TransactionType.PAYMENT_EXECUTION]: 'EPN',
  [TransactionType.VOID_ADJUSTMENT]: 'ANL',
  [TransactionType.CASH_DEPOSIT]: 'DEP',
  [TransactionType.OPERATING_EXPENSE]: 'GTO',
  [TransactionType.CASH_SESSION_OPENING]: 'APC',
  [TransactionType.CASH_SESSION_CLOSING]: 'CIE',
  [TransactionType.CASH_SESSION_TO_HUB_TRANSFER]: 'ACH',
  [TransactionType.CASH_SESSION_WITHDRAWAL]: 'RET',
  [TransactionType.CASH_SESSION_DEPOSIT]: 'ING',
  [TransactionType.CAPITAL_CONTRIBUTION]: 'CAP',
  [TransactionType.BANK_WITHDRAWAL_TO_SHAREHOLDER]: 'RAC',
  [TransactionType.CASH_WITHDRAWAL_TO_PETTY_CASH]: 'GCP',
};
