export enum AutomationActionType {
  CREATE_DERIVED_TRANSACTION = 'CREATE_DERIVED_TRANSACTION',
  GENERATE_LEDGER_ENTRIES = 'GENERATE_LEDGER_ENTRIES',
  UPDATE_STOCK = 'UPDATE_STOCK',
  CREATE_INSTALLMENTS = 'CREATE_INSTALLMENTS',
  UPDATE_INSTALLMENTS_FROM_PAYMENT = 'UPDATE_INSTALLMENTS_FROM_PAYMENT',
}

