import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  JoinColumn,
  CreateDateColumn,
  UpdateDateColumn,
  DeleteDateColumn,
  Unique,
  Index,
} from 'typeorm';
import { User } from '@modules/users/domain/user.entity';

// Enum con todos los permisos del sistema
// Sincronizado con lib/permissions.ts ABILITY_VALUES
export enum Ability {
  // Dashboard
  DASHBOARD_MENU = 'DASHBOARD_MENU',
  // Receptions
  RECEPTIONS_MENU = 'RECEPTIONS_MENU',
  RECEPTIONS_CREATE_MENU = 'RECEPTIONS_CREATE_MENU',
  RECEPTIONS_DELETE = 'RECEPTIONS_DELETE',
  RECEPTIONS_UPDATE_IMPURITY = 'RECEPTIONS_UPDATE_IMPURITY',
  RECEPTIONS_UPDATE_PRICE = 'RECEPTIONS_UPDATE_PRICE',
  RECEPTIONS_UPDATE_DATE = 'RECEPTIONS_UPDATE_DATE',
  RECEPTIONS_PRINT_DETAIL = 'RECEPTIONS_PRINT_DETAIL',
  // Producers
  PRODUCERS_MENU = 'PRODUCERS_MENU',
  PRODUCERS_CREATE = 'PRODUCERS_CREATE',
  PRODUCERS_UPDATE = 'PRODUCERS_UPDATE',
  PRODUCERS_DELETE = 'PRODUCERS_DELETE',
  PRODUCERS_PRINT_DETAIL = 'PRODUCERS_PRINT_DETAIL',
  PRODUCERS_CREATE_BANK_ACCOUNT = 'PRODUCERS_CREATE_BANK_ACCOUNT',
  PRODUCERS_UPDATE_BANK_ACCOUNT = 'PRODUCERS_UPDATE_BANK_ACCOUNT',
  PRODUCERS_DELETE_BANK_ACCOUNT = 'PRODUCERS_DELETE_BANK_ACCOUNT',
  // Productive Units
  PRODUCTIVE_UNITS_MENU = 'PRODUCTIVE_UNITS_MENU',
  PRODUCTIVE_UNITS_CREATE = 'PRODUCTIVE_UNITS_CREATE',
  PRODUCTIVE_UNITS_UPDATE = 'PRODUCTIVE_UNITS_UPDATE',
  PRODUCTIVE_UNITS_DELETE = 'PRODUCTIVE_UNITS_DELETE',
  // Seasons
  SEASONS_MENU = 'SEASONS_MENU',
  SEASONS_CREATE = 'SEASONS_CREATE',
  SEASONS_UPDATE = 'SEASONS_UPDATE',
  SEASONS_DELETE = 'SEASONS_DELETE',
  // Advances
  ADVANCES_MENU = 'ADVANCES_MENU',
  ADVANCES_CREATE = 'ADVANCES_CREATE',
  ADVANCES_DELETE = 'ADVANCES_DELETE',
  ADVANCES_PRINT_RECEIPT = 'ADVANCES_PRINT_RECEIPT',
  ADVANCES_DETAIL = 'ADVANCES_DETAIL',
  ADVANCES_UPDATE_DATE = 'ADVANCES_UPDATE_DATE',
  // Settlements
  SETTLEMENTS_MENU = 'SETTLEMENTS_MENU',
  SETTLEMENTS_VIEW = 'SETTLEMENTS_VIEW',
  SETTLEMENTS_CREATE = 'SETTLEMENTS_CREATE',
  SETTLEMENTS_UPDATE = 'SETTLEMENTS_UPDATE',
  SETTLEMENTS_DELETE = 'SETTLEMENTS_DELETE',
  SETTLEMENTS_PRINT_DETAIL = 'SETTLEMENTS_PRINT_DETAIL',
  SETTLEMENTS_UPDATE_DATE = 'SETTLEMENTS_UPDATE_DATE',
  // Admin Bank Accounts
  ADMIN_BANK_ACCOUNTS_MENU = 'ADMIN_BANK_ACCOUNTS_MENU',
  ADMIN_BANK_ACCOUNTS_VIEW = 'ADMIN_BANK_ACCOUNTS_VIEW',
  ADMIN_BANK_ACCOUNTS_CREATE = 'ADMIN_BANK_ACCOUNTS_CREATE',
  ADMIN_BANK_ACCOUNTS_UPDATE = 'ADMIN_BANK_ACCOUNTS_UPDATE',
  ADMIN_BANK_ACCOUNTS_DELETE = 'ADMIN_BANK_ACCOUNTS_DELETE',
  // Customers
  CUSTOMERS_MENU = 'CUSTOMERS_MENU',
  CUSTOMERS_CREATE = 'CUSTOMERS_CREATE',
  CUSTOMERS_UPDATE = 'CUSTOMERS_UPDATE',
  CUSTOMERS_DELETE = 'CUSTOMERS_DELETE',
  // Dispatches
  DISPATCHES_MENU = 'DISPATCHES_MENU',
  DISPATCHES_CREATE = 'DISPATCHES_CREATE',
  DISPATCHES_PRINT_DETAIL = 'DISPATCHES_PRINT_DETAIL',
  DISPATCHES_UPDATE_DATE = 'DISPATCHES_UPDATE_DATE',
  DISPATCHES_UPDATE_PRICE = 'DISPATCHES_UPDATE_PRICE',
  DISPATCHES_UPDATE_PALLETS = 'DISPATCHES_UPDATE_PALLETS',
  // Varieties
  VARIETIES_MENU = 'VARIETIES_MENU',
  VARIETIES_CREATE = 'VARIETIES_CREATE',
  VARIETIES_UPDATE = 'VARIETIES_UPDATE',
  VARIETIES_DELETE = 'VARIETIES_DELETE',
  // Formats
  FORMATS_MENU = 'FORMATS_MENU',
  FORMATS_CREATE = 'FORMATS_CREATE',
  FORMATS_UPDATE = 'FORMATS_UPDATE',
  FORMATS_DELETE = 'FORMATS_DELETE',
  // Trays
  TRAYS_MENU = 'TRAYS_MENU',
  TRAYS_CREATE = 'TRAYS_CREATE',
  TRAYS_UPDATE = 'TRAYS_UPDATE',
  TRAYS_DELETE = 'TRAYS_DELETE',
  TRAYS_AJUST_STOCK = 'TRAYS_AJUST_STOCK',
  TRAYS_DELIVERY = 'TRAYS_DELIVERY',
  TRAYS_RECEPTION = 'TRAYS_RECEPTION',
  // Audit
  AUDIT_MENU = 'AUDIT_MENU',
  // Users
  USERS_MENU = 'USERS_MENU',
  USERS_CREATE = 'USERS_CREATE',
  USERS_UPDATE = 'USERS_UPDATE',
  USERS_DELETE = 'USERS_DELETE',
}

// Lista de todos los valores del enum para iterar
export const ALL_ABILITIES = Object.values(Ability);

@Unique(['userId', 'ability'])
@Entity('permissions')
export class Permission {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Index()
  @Column({ type: 'uuid', nullable: true })
  userId?: string;

  @ManyToOne(() => User, {
    nullable: true,
    onDelete: 'SET NULL',
  })
  @JoinColumn({ name: 'userId' })
  user!: User;

  @Column({ type: 'varchar', length: 100 })
  ability!: string;

  @Column({ type: 'varchar', length: 255, nullable: true })
  description?: string;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;

  @DeleteDateColumn()
  deletedAt?: Date;
}
