import type { ReportRegistryEntry } from "./types/sales-report.types";

export const SALES_REPORT_REGISTRY: ReportRegistryEntry[] = [
  {
    id: "sales-by-period",
    title: "Resumen de ventas",
    description: "Totales, ticket promedio y evolución diaria.",
    wave: "mvp",
    category: "resumen",
    params: [
      { kind: "dateRange", required: true },
      { kind: "branch" },
      { kind: "posMulti" },
      { kind: "granularity" },
      { kind: "compareWith" },
    ],
  },
  {
    id: "sales-detail",
    title: "Detalle de ventas",
    description: "Listado de ventas con gráfico diario.",
    wave: "mvp",
    category: "resumen",
    params: [
      { kind: "dateRange", required: true },
      { kind: "branch" },
      { kind: "posMulti" },
      { kind: "customer" },
      { kind: "paymentMethod" },
      { kind: "granularity" },
    ],
  },
  {
    id: "sales-period-compare",
    title: "Comparativo de período",
    description: "Ventas del período vs período anterior o mismo lapso del año pasado.",
    wave: "p1",
    category: "comparativos",
    params: [
      { kind: "dateRange", required: true },
      { kind: "branch" },
      { kind: "posMulti" },
      { kind: "granularity" },
      { kind: "compareWith" },
    ],
  },
  {
    id: "pos-compare",
    title: "Comparativo entre POS",
    description: "Compara dos puntos de venta lado a lado en el mismo período.",
    wave: "p1",
    category: "comparativos",
    params: [
      { kind: "dateRange", required: true },
      { kind: "branch" },
      { kind: "posPair" },
    ],
  },
  {
    id: "sales-by-product",
    title: "Ventas de un producto",
    description: "Unidades, monto y margen de un producto.",
    wave: "mvp",
    category: "productos",
    params: [
      { kind: "dateRange", required: true },
      { kind: "product", required: true },
      { kind: "branch" },
      { kind: "posMulti" },
    ],
  },
  {
    id: "top-products",
    title: "Productos más vendidos",
    description: "Ranking por monto y margen.",
    wave: "p1",
    category: "productos",
    params: [
      { kind: "dateRange", required: true },
      { kind: "topN", default: 20 },
      { kind: "branch" },
      { kind: "posMulti" },
      { kind: "compareWith" },
    ],
  },
  {
    id: "sales-by-category",
    title: "Ventas por categoría",
    description: "Agregado por categoría de producto.",
    wave: "p1",
    category: "productos",
    params: [
      { kind: "dateRange", required: true },
      { kind: "branch" },
      { kind: "posMulti" },
      { kind: "compareWith" },
    ],
  },
  {
    id: "customer-returns",
    title: "Devoluciones de cliente",
    description: "Devoluciones del período y ratio vs ventas.",
    wave: "mvp",
    category: "clientes",
    params: [
      { kind: "dateRange", required: true },
      { kind: "customer" },
      { kind: "product" },
      { kind: "branch" },
      { kind: "posMulti" },
    ],
  },
  {
    id: "customer-purchases",
    title: "Compras de un cliente",
    description: "Historial y margen de un cliente.",
    wave: "mvp",
    category: "clientes",
    params: [
      { kind: "dateRange", required: true },
      { kind: "customer", required: true },
    ],
  },
  {
    id: "credit-notes",
    title: "Notas de crédito",
    description: "NC emitidas a clientes.",
    wave: "p1",
    category: "clientes",
    params: [{ kind: "dateRange", required: true }, { kind: "customer" }],
  },
  {
    id: "cash-session-close",
    title: "Cierre de sesión de caja",
    description: "Mix de pagos de una sesión o rango/POS.",
    wave: "mvp",
    category: "caja_pagos",
    params: [
      { kind: "cashSession" },
      { kind: "dateRange", required: false },
      { kind: "branch" },
      { kind: "posMulti" },
    ],
  },
  {
    id: "sales-by-payment-method",
    title: "Mix de medios de pago",
    description: "Distribución de ventas por medio de pago.",
    wave: "p1",
    category: "caja_pagos",
    params: [
      { kind: "dateRange", required: true },
      { kind: "branch" },
      { kind: "posMulti" },
      { kind: "compareWith" },
    ],
  },
  {
    id: "sales-by-pos",
    title: "Comparativo por punto de venta",
    description: "Ventas agregadas por POS.",
    wave: "p1",
    category: "canales",
    params: [
      { kind: "dateRange", required: true },
      { kind: "branch" },
      { kind: "compareWith" },
    ],
  },
  {
    id: "quotations-funnel",
    title: "Embudo de cotizaciones",
    description: "Cotizaciones por estado.",
    wave: "p1",
    category: "pipeline",
    params: [{ kind: "dateRange", required: true }],
  },
  {
    id: "backorders-status",
    title: "Encargos por estado",
    description: "Backorders en el período.",
    wave: "p1",
    category: "pipeline",
    params: [{ kind: "dateRange", required: true }],
  },
  {
    id: "promotion-redemptions",
    title: "Uso de promociones",
    description: "Redenciones de promociones.",
    wave: "p1",
    category: "promociones",
    params: [{ kind: "dateRange", required: true }],
  },
];

export function getReportEntry(id: string): ReportRegistryEntry | undefined {
  return SALES_REPORT_REGISTRY.find((r) => r.id === id);
}
